# This is a basic workflow to help you get started with Actions

name: XMLtoJSONpipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "transform"
  transform:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Display a file from the repo
      - name: display file
        run: cat README.md
      
      # Create a file
      - name: create file
        run: |
          printf "Hello\nWorld\n" > hw.txt

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: use node.js
        uses: actions/setup-node@v3.4.1
        
      - name: install xml-js
        run: npm install xml-js
        
      - name: log json
        run: node ./convertXML.js
        
      - name: display temp file content
        run: node console.log(2+2)


      
